version: '3'

services:
  app:
    container_name: 'todo'
    build: .
    volumes:
      - .:/homework/app
      - node_modules:/app/node_modules
    ports:
      - 3100:3100
    depends_on:
      - postgres
    stdin_open: true
    environment:
      - PORT=3000

    command: npm start
  postgres:
    image: postgres:16
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB = todo
     - PORT = 5433
    ports:
      - '5433:5433'
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  node_modules:
  postgres: